# Generated by Django 5.0.6 on 2024-06-17 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
